[build]
target = "xtensa-esp32-espidf"

[target.xtensa-esp32-espidf]
# rustflags = ["--cfg", "espidf_time64", "-C", "default-linker-libraries"]
rustflags = ["-C", "default-linker-libraries"]
runner = "espflash flash --monitor"
# linker = "ldproxy"

[unstable]
build-std = ["std", "panic_abort"]

[env]
ESP_IDF_VERSION = "v4.4.6"
MCU="esp32"

