[build]
target = "xtensa-esp32-espidf"

[target.xtensa-esp32-espidf]
linker = "ldproxy"
# rustflags = ["--cfg", "espidf_time64"]
# rustflags = ["-C", "default-linker-libraries"]
runner = "espflash flash --monitor"
# linker = "ldproxy"

[unstable]
build-std = ["std", "panic_abort"]

[env]
# ESP_IDF_VERSION = "release/v5.0"
MCU="esp32"

